[build]
  # Build command
  command = "npm run build:netlify"
  
  # Publish directory (for static files)
  publish = "public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # Configure secrets scanning
  SECRETS_SCAN_OMIT_PATHS = ".env.example,NETLIFY_DEPLOYMENT.md,README.md,sfdx-project.json,dist/"
  SECRETS_SCAN_OMIT_KEYS = "SF_LOGIN_URL"

# Redirect rules
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/mcp/tools/list"
  to = "/.netlify/functions/tools-list"
  status = 200

[[redirects]]
  from = "/mcp/tools/call"
  to = "/.netlify/functions/tools-call"
  status = 200

# Catch-all redirect for SPA behavior (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Environment variables (these will need to be set in Netlify dashboard)
# Required OAuth 2.0 variables:
# SF_LOGIN_URL
# SF_CLIENT_ID
# SF_CLIENT_SECRET
# SLACK_WEBHOOK_URL